<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\form\\autocomplete' => '/../src/Autocomplete.php',
                'rapture\\form\\button' => '/../src/Button.php',
                'rapture\\form\\checkbox' => '/../src/Checkbox.php',
                'rapture\\form\\collection' => '/../src/Collection.php',
                'rapture\\form\\csrf' => '/../src/Csrf.php',
                'rapture\\form\\date' => '/../src/Date.php',
                'rapture\\form\\div' => '/../src/Div.php',
                'rapture\\form\\element' => '/../src/Element.php',
                'rapture\\form\\file' => '/../src/File.php',
                'rapture\\form\\form' => '/../src/Form.php',
                'rapture\\form\\hidden' => '/../src/Hidden.php',
                'rapture\\form\\img' => '/../src/Img.php',
                'rapture\\form\\number' => '/../src/Number.php',
                'rapture\\form\\password' => '/../src/Password.php',
                'rapture\\form\\radio' => '/../src/Radio.php',
                'rapture\\form\\reset' => '/../src/Reset.php',
                'rapture\\form\\select' => '/../src/Select.php',
                'rapture\\form\\submit' => '/../src/Submit.php',
                'rapture\\form\\text' => '/../src/Text.php',
                'rapture\\form\\textarea' => '/../src/Textarea.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
